### ISSUE TITLE
Unit not showing up in build menu

### ISSUE THREAD

**Issue by rishubn** [JustinLove/baboom#1]
How do I build this unit? IT's not showing up in t1 or t2 bot factories

**Comment by JustinLove** [comment]
It should be in the advanced bot factory.

Can you start a game (AI skirmish should be fine) with BaBoom and [PA-Diag](https://forums.uberent.com/threads/rel-pa-diag-1-1-0-87296.66208/), and send me the diag report?  Attach here, or forum PM if you like; forums might need to be zipped because of file type limits.

**Comment by rishubn** [comment]
Looks like I had another mod enabled but I didn't realize it. There was a conflict
